version: 2
jobs:
  build:
    docker:
      - image: determinant/spatial-arch:0.1.1
    working_directory: /usr/src/landshark
    steps:
      - checkout
      - run: mkdir -p test_output/pytest test_output/flake8 test_output/coverage test_output/mypy
      - run: pip install .[dev]
      - run: make test-xml
      - run: make typecheck-xml
      - run: make lint-xml
      - run: make integration-xml
      - store_artifacts:
          path: test_output/coverage
          destination: reports
      - store_test_results:
          path: test_output/
